fname=Notes_about_network_propagation
baname=BachelorThesis
#Notes_about_network_propagation.pdf: Notes_about_network_propagation.tex mybib.bib
#	pdflatex $(fname)
#	biber $(fname)
#	pdflatex $(fname)

BachelorThesis.pdf: BachelorThesis.tex mybib.bib
	pdflatex $(baname)
	biber $(baname)
	pdflatex $(baname)
