#fname=Notes_about_network_propagation
#baname=BachelorThesis
baname=thesis
#Notes_about_network_propagation.pdf: Notes_about_network_propagation.tex mybib.bib
#	pdflatex $(fname)
#	biber $(fname)
#	pdflatex $(fname)

Thesis.pdf:
	pdflatex $(baname)
	biber $(baname)
	pdflatex $(baname)
